name: discovery-server

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.DEPLOY_TOKEN }}
    - name: Build the Docker image
      run: |
        docker build . --tag ghcr.io/dargor94/discovery-server:latest
        docker push ghcr.io/dargor94/discovery-server:latest
        docker run ghcr.io/dargor94/discovery-server:latest

